<?php
use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

/**
 * Implements hook_page_attachments().
 */

function ws_task_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'ws_task/common_js_css';
}


/**
 * Implements hook_theme().
 */
function ws_task_theme($existing, $type, $theme, $path) {
  return array(
    'task_dashboard' => array(
      'variables' => array('task_dashboard' => NULL),
    ),    
    'tabular_task' => array(
      'variables' => array('task_lists' => NULL),
    ),
  );
}